

Words_list = [
    {"word": "Carbon", "question": "A chemical element"},
    {"word": "Real", "question": "A Currency"},
    {"word": "Modric", "question": "Player for Real Madrid"},
    {"word": "Everest", "question": "The highest mountain"},
    {"word": "They", "question": "a Pronoun"},
    {"word": "Gold", "question": "ِVery expensive"},
    {"word": "Iraq", "question": "Mesopotamia"},
    {"word": "Audi", "question": "German car"},
    {"word": "for", "question": "A preposition"},
    {"word": "Golf", "question": "A favorite Sport for Rich"},
    {"word": "lago", "question": " What is the name of the main antagonist in the Shakespeare play Othello "},
    {"word": "four", "question": "How many human players are there on each side in a polo match ?"},     {
        "word": "feb", "question": " Which month of the year has the least number of days"},
    {"word": "sty", "question": " Where does a pig live?"},
    {"word": "nose", "question": " We smell with our?"},
    {"word": "tibet", "question": " Which place is known as the roof of the world?"},
    {"word": "tin", "question": " What element is denoted by the chemical symbol Sn in the periodic table?"},
    {"word": "krone", "question": " What is the currency of Denmark?"},
    {"word": "knee", "question": " In which part of your body would you find the cruciate ligament?"},
    {"word": "east", "question": " In which direction does the sun rise ?"},
    {"word": "Yemen", "question": "Country?"},
    {"word": "Forg", "question": "Country?"},
    {"word": "yes", "question": "Anser?"},
    {"word": "July", "question": "The seventh month of the year"},
    {"word": "Python", "question": "A programming language"},
    {"word": "ِAlgeria", "question": "The biggest country in Africa"},
    {"word": "Happy", "question": "Opposite of sad"},
    {"word": "Manila", "question": "The capital of the Philippines"},
    {"word": "Tigris", "question": "ِA river in Iraq"},
    {"word": "Joe Biden", "question": "The president of America "},
    {"word": "Abdel Halim Hafez", "question": "An Egyptian singer"},
    {"word": " censorious", "question": "The synonym of critical"},
    {"word": "S400", "question": "Air missile system"},
    {"Word": "orang", "quest": "what is orang color?"},
    {"Word": "red", "quest": "what is appale color?"},
    {"Word": "yallow", "quest": "what is banana color?"},
    {"Word": "rose", "quest": "what is Strawberry color?"},
    {"Word": "green", "quest": "what is watermelon color?"},
    {"Word": "black", "quest": "what is Grape color?"},
    {"Word": "blue", "quest": "what is Cranberries color?"},
    {"Word": "white", "quest": "what is fig color?"},
    {"Word": "browen", "quest": "what is Kiwi color?"},
    {"Word": "darkgreen", "quest": "what is avocado color?"},
    {"word": "songs", "question": "which You listen everyday?"},
    {"word": "nliy", "question": "Her most important work is a movie and men.?"},
    {"word": "Om Klthom", "question": "The Lady of Arabic Singing?"},
    {"word": "pm", "question": "night time?"},
    {"word": "gta", "question": " still car  game?"},
    {"word": "china", "question": "From Southeast Asian countries?"},
    {"word": "go", "question": "form somewhere?"},
    {"word": "Sun", "question": "the biggest start in our galaxy?"},
    {"word": "okay", "question": "when everything is fain?"},
    {"word": "spong pop", "question": "Who lives in the sea and people are loved it ?"},
    {"word": "left", "question": "Which way is anti-clockwise, left or righ?"},
    {"word": "lgloo", "question": " What do you call a house made of ice?"},
    {"word": "nile", "question": " Which is the longest river on the earth?"},
    {"word": "Japan", "question": "Which country is called the land of rising sun?"},
    {"word": "mars", "question": " Which planet is known as the Red Planet?"},
    {"word": "skin", "question": " Which is the most sensitive organ in our body?"},
    {"word": "India", "question": " The largest 'Democracy' in the world?"},
    {"word": "water",
        "question": "What makes up (approx.) 80% of our brain's volume?"},
    {"word": "Ghana", "question": " Which African nation is famous for chocolate?"},
    {"word": "red", "question": "What is the top color in a rainbow?"},
    {"word": "lago", "question": " What is the name of the main antagonist in the Shakespeare play Othello "},
    {"word": "four", "question": "How many human players are there on each side in a polo match ?"},
    {"word": "feb", "question": " Which month of the year has the least number of days"},
    {"word": "sty", "question": " Where does a pig live?"},
    {"word": "nose", "question": " We smell with our?"},
    {"word": "tibet", "question": " Which place is known as the roof of the world?"},
    {"word": "tin", "question": " What element is denoted by the chemical symbol Sn in the periodic table?"},
    {"word": "krone", "question": " What is the currency of Denmark?"},
    {"word": "knee", "question": " In which part of your body would you find the cruciate ligament?"},
    {"word": "east", "question": " In which direction does the sun rise ?"},
    {"word": "Sky", "question": "something is starting with s \'b\'"},
    {"word": "Sedney", "question": "A capital city of Australia"},
    {"word": "Popup", "question": "Alert message"},
    {"word": "FTP", "question": "standard for File Transfer Protocol"},
    {"word": "Taxes", "question": "The position of Dallas"},
    {"word": "Islam", "question": "What your religion"},
    {"word": "Team", "question": "meaning of co-workers"},
    {"word": "Koyoto", "question": "The name of Japan anime city \'C\'"},
    {"word": "Vaccine", "question": "Synonym of medicine"},
    {"word": "Dark", "question": "The opposite of \'light\'"},
    {"word": "songs", "question": "which You listen everyday?"},
    {"word": "lion", "question": "who is the king of the jungle?"},
    {"word": "Om Klthom", "question": "The Lady of Arabic Singing?"},
    {"word": "Oval", "question": "Shape of Egg is?"},
    {"word": "Pluto", "question": " It is one of the planets of the solar system?"},
    {"word": "china", "question": "From Southeast Asian countries?"},
    {"word": "purple", "question": "it is mean I trust You?"},
    {"word": "Sun", "question": "the biggest start in our galaxy?"},
    {"word": "Roma", "question": "one of Italia country?"},
    {"word": "sponge pop", "question": "Who lives in the sea and people are loved it ?"},
    {"word": "Tokyo", "question": "Asia's largest city"},
    {"word": "Australia", "question": "The largest island in the world"},
    {"word": "Washington", "question": "What is the capital of America"},
    {"word": "Nile", "question": "The longest river in the world"},
    {"word": "Whale", "question": "The heaviest animal on earth"},
    {"word": "Jupiter", "question": "The largest planet in the solar system"},
    {"word": "Algorithm", "question": "Founder of Algebra"},
    {"word": "Asia", "question": "Largest continents"},
    {"word": "Ostrich", "question": "The fastest bird in the world"},
    {"word": "London", "question": "The city is located the famous Big Ben Watch"},
    {"word": "Friday", "question": "the last day from week?"},
    {"word": "seven", "question": "number of days in week"},
    {"word": "france", "question": "where is effil tower"},
    {"word": "sanaa", "question": "the capital of yemen"},
    {"word": "Cairo", "question": "the capital of Egypt"},
    {"word": "iraq", "question": "Baghdad is a capital of"},
    {"word": "cars", "question": "a taxi is a type of?"},
    {"word": "Egypt", "question": " where is The Nile River'"},
    {"word": "Yemen", "question": "where is Socotra Island"},
    {"word": "Amina", "question": " mother of our massenger"},
    {"word": "Bahrain", "question": "A gulf country that starts with \'b\'"},
    {"word": "Brazil", "question": "A country that hosted World Cup in 2014"},
    {"word": "Cheap", "question": "Opposite of expensive"},
    {"word": "Ready", "question": "A word describing a state"},
    {"word": "Nivada", "question": "The state where Las Vegas is located"},
    {"word": "House", "question": "Where you live"},
    {"word": "Bus", "question": "A form of public transportation"},
    {"word": "Canada", "question": "A country in South America that starts with the letter \'C\'"},
    {"word": "Need", "question": "A word similar to require"},
    {"word": "Die", "question": "The opposite of \'live\'"},
    {"word": "CPU", "question": "Brain of computer is?"},
    {"word": "Camel", "question": "Which animal has hump on its back?"},
    {"word": "Jasmine", "question": "flower is white in colour?"},
    {"word": "Oval", "question": "Shape of Egg is?"},
    {"word": "Winter", "question": " In which season we wear warm clothes?"},
    {"word": "Seven", "question": "colors are there in a rainbow?"},
    {"word": "Red", "question": "primary color?"},
    {"word": "Sun", "question": "principal source of energy for earth?"},
    {"word": "Africa", "question": "continent is known as 'Dark' continent?"},
    {"word": "Asia", "question": "the largest continent in the world?"},
    {"word": "after", "question": "Behind in place or order"},
    {"word": "draft", "question": "A current of air in an enclosed area."},
    {"word": "call", "question": "To say in a loud voice"},
    {"word": "little", "question": "Small in size"},
    {"word": "option", "question": "The act of choosing"},
    {"word": "signal", "question": "A message communicated by such means."},
    {"word": "writer", "question": "a person engaged in writing books"},
    {"word": "follow", "question": "To come or go after"},
    {"word": "camera", "question": " a hand-held photographic device"},
    {"word": "detail", "question": "An individual part or item"},
    {"word": "action", "question": "process of being active"},
    {"word": "beauty", "question": "One that is beautiful, especially a beautiful woman."},
    {"word": "center", "question": "A point or place that is equally distant from the sides "},
    {"word": "detect", "question": "To learn something hidden and"},
    {"word": "orange", "question": "Of the color orange."},
    {"word": "finish", "question": "to stop"},
    {"word": "online", "question": "Connected to a central computer or to a computer network"},
    {"word": "player", "question": "A gambler."},
    {"word": "later", "question": "afterwards"},
    {"word": "dog", "question": " A male animal of the family Canidae"},
    {"word": "nine", "question": "One of the numbers"},
    {"word": "red", "question": "A color"},
    {"word": "ِdone", "question": "We say it when we have finished"},
    {"word": "sad", "question": "Feeling"},
    {"word": "rice", "question": "Kind of food"},
    {"word": "suger", "question": "ِWhat makes sweets sweety?"},
    {"word": "salt", "question": "Very similer to suger"},
    {"word": "mark", "question": "Who created facebook"},
    {"word": "bad", "question": "The opposite of good"},
    {"word": "dirty", "question": "The opposite of cleen"},
    {"word": "march", "question": "What is third month a year? "},
    {"word": "cancer", "question": "Very dangerous disease? "},
    {"word": "Mania", "question": "What is a five-letter word meaning 'insanity'? "},
    {"word": "January", "question": "What is first month in a year? "},
    {"word": "Mallet", "question": "What is a six-letter word meaning 'a wooden hammer'? "},
    {"word": "clock", "question": "Smoething shows the time? "},
    {"word": "Mantle", "question": "What is a six-letter word meaning 'a cloak'? "},
    {"word": "car", "question": "Sonmethinge you drive? "},
    {"word": "Manor", "question": "What is a five-letter word meaning 'the landed estate of a lord or nobleman'? "},
    {"word": "in", "question": "charcter use to point for inside some thing"},
    {"word": "on", "question": "charcter use to point for above some thing"},
    {"word": "water", "question": "i am  with out smell or test "},
    {"word": "pen", "question": "u need me when u want to write in paper"},
    {"word": "at", "question": " charcter use to point for time"},
    {"word": "bad", "question": "some thing u sleep in"},
    {"word": "int", "question": "use to declare number in program"},
    {"word": "winter", "question": "falling snew in my season"},
    {"word": "ntural", "question": "when call something orginal u mean"},
    {"word": "add", "question": "the name  of the opreator +"},

]
